### PR TITLE
deploy pkgdown to ghpages

### PR DESCRIPTION
**Pull request by andybeet**
Pkgdown site created as a means to review documentation. None of this is set in stone. Addition/omission of content should be discussed prior to merging pull request

## Restructure

* Added `docs` folder to .gitignore and removed all content in `docs` folder
* Created a `workshop` folder to hold the `rmds` created for the workshops
* `workshop/indexmain.html` will be a hidden landing page for the rmd visualization
* moved pkgdown.yml to `pkgdown` folder,  removed old entries, added missing entries

## Documentation

* Several data sets did not have documentation. Added place holders for: 
   -  `lps_sharks.r`,
   - `long_line_surevy.r`,
   - `longlinesurbey.sf.r`
   -  `ches_bay_sf.r` 
   - `hp_density.r`
* Removed old documentation referencing data sets no longer in package
* Cleaned up readme.rmd and added info (main branch = released, dev = current cycle)
* Moved rmd's to vignettes folder
   - `landing_page`
   - `geom_gls`
   - `data_guidelines`
   - `ecodata_maintenance`
* Reworked `ecodata.rmd` which displays as `Getting started` on pkgdown site
* Added Brandon as new maintainer

## View changes
* In Rstudio switch to `andy_ghpages` branch
* `pkgdown::build_site()`. all pages are deployed into local docs folder
* To view `workshop` visualizations edit url from `docs/index.html` to `workshop/indexmain.html`

### CODE REVIEW

**Comment by andybeet** [comment]
@slucey @sgaichas @BBeltz1 
The pkgdown site is ready to review.
In Rstudio, switch to `andy_ghpages` branch then type `pkgdown::build_site()`
All website content will be in the `docs` folder. This folder is now gitignored

**Comment by BBeltz1** [comment]
@andybeet At first glance, the site looks great. I'll go through it more thoroughly. I'm wondering if we should add a description or disclaimer about our new dev branch workflow... something so users are aware that 'master' will only be updated at specific, infrequent SOE milestones and that they must pull from the dev branch to have the most up-to-date version.

**Comment by slucey** [comment]
Looks good to me.  We can obviously tweak things as we go along.  One major enhancement that we'll need to do if update the metadata for each data set to include the variable names and brief descriptions.

**Comment by andybeet** [comment]
@BBeltz1 @slucey @sgaichas So Kim had the Rmd's for the current developing cycle (that would be used in the workshops) live online, and still has. eg [MAB-LTL](https://noaa-edab.github.io/ecodata/LTL_MAB#Mid-Atlantic_Bight). These are currently "hidden" in the sense that there are no links provided to view them, meaning you need to know the address to view them. Do we want to do the same thing going forward? I am assuming we would. The alternative would be adding them as vignettes to the package.

**Comment by slucey** [comment]
@andybeet I think there was a link on the landing page ([MAB LTL](https://noaa-edab.github.io/ecodata/LTL_MAB)).  That was the only way I ever knew how to find them.  So it might be good to have them as vignettes that we can look at.

**Comment by BBeltz1** [comment]
@andybeet The pkgdown site looks great to me.

**Review by sgaichas — APPROVED** [review]
The site builds locally for me and looks great. Thanks!
I noticed the forage_index dataset is missing documentation as well, but that should not prevent merging these changes; it can be added later.

**Review by BBeltz1 — APPROVED** [review]
Site also builds for me locally and looks great.

**Pull request merged**
