### PR TITLE
Short trend install

### PR DESCRIPTION
**Pull request by BBeltz1**
# Installed short term trend in the following plot functions:

- plot_SAV.R
- plot_aggregate_biomass.R*
- plot_bottom_temp.R*
- plot_bottom_temp_comp.R
- plot_bottom_temp_glorys.R
- plot_ches_bay_wq.R
- plot_cold_pool.R
- plot_comdat.R
- plot_exp_n.R
- plot_forage_anomaly.R
- plot_forage_index.R
- plot_function_template.R
- plot_gom_salmon.R
- plot_heatwave.R
- plot_hudson_river_flow.R
- plot_long_term_sst.R
- plot_mab_inshore_survey.R
- plot_mass_inshore_survey.R*
- plot_recdat.R
- plot_seabird_ne.R
- plot_seasonal_oisst_anom.R
- plot_spawn_timing.R*
- plot_species_dist.R*
- plot_storminess.R
- plot_survey_shannon.R*
- plot_trans_dates.R
- plot_zoo_abundance_anom.R*
- plot_zoo_diversity.R*
- plot_zoo_strat_abun.R*

*Datasets have missing years for some variables, which prevent short term trend analysis. These datasets will be corrected when updated for 2025. Plot functions have an added safeguard and will work as normal so long as variable `n` is not specified.

### CODE REVIEW

**Comment by andybeet** [comment]
All looks good  other than `plot_mab_inshore_survey`. Seems like all fits are commented out. Is there a reason for that?

**Comment by BBeltz1** [comment]
I did not comment out `geom_gls`, it was already commented out. So when I added `geom_lm`, I commented it out for consistency. I wanted to find out why `geom_gls` was turned off before turning either on.

**Comment by andybeet** [comment]
ok. sounds good.

**Comment by andybeet** [comment]
Also, this is just a subset of the plot functions. Is that because these are the only ones that are a line graph?

**Pull request merged**
