### PR TITLE
Rename datasets

### PR DESCRIPTION
**Pull request by BBeltz1**
## Renamed `ecodata` datasets
- `HMS_species_distribution` renamed to `cetacean_dist`
- `bottom_temp` renamed to `bottom_temp_insitu`
- `bottom_temp_comp` renamed to `bottom_temp_model_anom`
- `bottom_temp_seasonal_gridded` renamed to `bottom_temp_model_gridded`
- `thermal_habitat_persistence` renamed to `thermal_habitat_gridded`
- `seasonal_sst_anomaly_gridded` renamed to `seasonal_oisst_anom_gridded`

### CODE REVIEW

**Comment by BBeltz1** [comment]
Closes #161

**Review by sgaichas — APPROVED** [review]
Thank you, this looks good, the plot functions work for me.

I updated the name for the cetacean_dist plot, I think the rest are good

Not related to this, I added a year title to the thermal habitat gridded plot. It would be great to add year to the OISST gridded dataset as well so we can do the same.

One issue not related to this PR but noting for later: 

We'll need to ensure missing years are filled with NA for the short term trend to work, bottom temp in situ fails with argument n=10 right now
```
> ecodata::plot_bottom_temp_insitu(n=10)
Error in check_data_validation(dataSet) : 
  Time (x field) is not equally spaced. You can not apply this test.
         You will need to explicitly add the missing Time value(s) using NA for the response(s)
Warning message:
Computation failed in `stat_lm()`.
Caused by error in `linear_ar1$pValue`:
! $ operator is invalid for atomic vectors
```

**Comment by sgaichas** [comment]
A bigger plot function change would be to add a year argument to the function call for `plot_bottom_temp_model_gridded` so that we can visualize different years, along with a year title for the plot. I can add this as an issue if we want

**Comment by jcaracappa1** [comment]
Also confirming that plot functions work for me.

**Comment by BBeltz1** [comment]
@sgaichas Yes please add as an issue, thanks.

**Pull request merged**
