### PR TITLE
Pull data review preparations into `dev`

### PR DESCRIPTION
**Pull request by BBeltz1**
### Updates to the following datasets:

- ecosystem overfishing (ppr)
- seasonal_oisst_anom_gridded
- trans_dates

### Added short term trend analysis to the following plot functions:

- plot_commercial_div.Rd
- plot_ichthyo_diversity.Rd
- plot_nao.Rd
- plot_ne_inshore_survey.Rd
- plot_observed_sharks.Rd
- plot_slopewater.Rd
- plot_wcr.Rd
- plot_wind_revenue.Rd

### CODE REVIEW

**Comment by BBeltz1** [comment]
Closes #176

**Comment by BBeltz1** [comment]
@andybeet @sgaichas This PR contains mostly preparation for yesterday's data review. There are a few data updates, `geom_lm` has been added to several plots, the poly fit was turned off in `geom_gls` and there's a large batch of comparison docs, which were shown yesterday. This shouldn't need major review, as everything in this PR was reviewed yesterday and any issues have been flagged as an action item or Github issue. That said, please let me know if you notice anything needing immediate attention.

**Review by andybeet — APPROVED** [review]
looks good

**Comment by sgaichas** [comment]
When I pulled this in there was a gitleaks fail
https://github.com/NOAA-EDAB/ecodata/actions/runs/12323766236

**Pull request merged**
