### PR TITLE
Update existing and add new ecodata datasets

### PR DESCRIPTION
**Pull request by BBeltz1**
The following datasets were added or updated:

- seasonal_sst_anomaly_gridded
- heatwave
- heatwave_year
- wind_dev_speed
- wcr
- annual_chl_pp
- seasonal_oisst_anom

### CODE REVIEW

**Comment by BBeltz1** [comment]
@andybeet batch of ecodata corrections and updates needs review. let me know if you find any issues. Kim's new `annual_chl_pp` indicator will need a new plot function.

**Comment by andybeet** [comment]
what is the rationale for a new indicator (`annual_chl_pp`)? Could we have not added the new variables to the current `chl_pp indicator`? There is already an ANNUAL_PPD_MEDIAN. Why not add ANNUAL_PPD_MEAN and the other two variables?

**Review by sgaichas — COMMENTED** [review]
in `wind_dev_speed` we need to reconcile variable names. Looks like 
Tot_Area_Acres in the previous datasets is Acres for report year 2024. 
Is there metadata to help get these aligned? Thanks

```
> unique(ecodata::wind_dev_speed$Var)
 [1] "Tot_Area_Acres"  "Num_Foundations" "Cable_Acres"     "Cable_Miles"    
 [5] "Num_Projects"    "Acres"           "Gen_Cap"         "Fndns"          
 [9] "Exp_Cab"         "Inter_Cab"       "Cab_Total" 
```

**Comment by BBeltz1** [comment]
The new indicator is the new data file that Kim H provided at this morning's stand up. I proposed the two options: include as new variables to the existing `chl_pp` indicator, OR create a new indicator to house the new variables. I believe Sarah and Kim chose the latter.

**Comment by sgaichas** [comment]
@andybeet we could have all the new stuff from Kim in the `chl_pp` dataset, but this was adding 4 new variables as I understood it, and all are annual instead of within year, so I thought it might be simpler/faster. I don't have strong opinions about this though so it could all be in one.

**Comment by BBeltz1** [comment]
I will take a second look at `wind_dev_speed` now.

**Comment by andybeet** [comment]
i think we need to look at PP and CHL after the cycle. For now let's leave it

**Review by andybeet — APPROVED** [review]
All datasets look ok and dont break any existing plotting functions

**Comment by BBeltz1** [comment]
@sgaichas the variable names in `wind_dev_speed` are aligned with last year's submission, but this may be why year2023 did not appear in the plot for last report. I can rework these variable names to match 2021 and 2022, as well as fix the last year's 2023 variables so that years 2023 and 2024 appear on this year's report.

**Comment by sgaichas** [comment]
for `wind_dev_speed` I get 3 report years, 21, 22, and 24, so either we are missing 2023 or the year naming conventions differed (21 and 22 data in 22 and 23 reports?). If there is a way to tell, I think we should also reconcile the `Report_year` field to be consistent. 

```
> unique(ecodata::wind_dev_speed$Report_year)
[1] "year2021" "year2022" "year2024"
```

**Comment by BBeltz1** [comment]
@sgaichas there were issues present last year that persisted through this year's submission as well. that is why only 2021 and 2022 were plotted previously. these issues should now be corrected and we should be able to plot all years that have data. note: Angela told me that each year, these data become more and more aggregated. you'll now find that when plotting this dataset, all years after 2025 have been aggregated... previously, they remained separated until 2030.

**Review by sgaichas — APPROVED** [review]
thanks for the fix in the `wind_dev_speed` dataset, all years plot now.
(Note: we will need to amend the `plot_wind_dev_speed` function line 49 to have labels for 2023 and 2024)

**Pull request merged**
