### PR TITLE
Pull large batch of SOE 2025 data updates into dev

### PR DESCRIPTION
**Pull request by BBeltz1**
# Processed data updates for the following:

- recdat
- stock_status
- abc_acl
- aggregate_biomass
- chl_pp
- exp_n
- engagement
- harborporpoise
- grayseal
- narw
- forage_index
- cold_pool
- spawn_timing
- trans_dates
- productivity_anomaly
- energy_density
- wea_landings_rev
- bottom_temp
- bottom_temp_comp
- bottom_temp_seasonal_gridded
- ches_bay_wq
- commercial_div
- gom_salmon
- hudson_river_flow
- mab_inshore_survey
- mass_inshore_survey
- SAV
- seasonal_oisst_anom
- slopewater
- species_groupings
- survey_shannon
- benthic_index
- community_climate_vulnerability
- zooplankton_index
- cetacean_acoustic
- wea_sound
- finfish_traits
- shoreside_support

### Includes minor changes to most get_scripts and some plot functions

### CODE REVIEW

**Comment by andybeet** [comment]
so did you run all of these through their plot functions? just wondering how much testing i need to do

**Comment by andybeet** [comment]
And ... it seem like we need to create plot functions for some of these also. Is that right? (shoreside_support, finfish_traits)

**Comment by BBeltz1** [comment]
Yes, I've plotted all datasets after updating and compared with the plots from last year.

And yes, the new indicators still need plot functions. Some of the contributors sent along plotting code we can use. Some sent images without code. I've followed up with contributors about supplying us with plotting code, but not all have gotten back to me.

**Comment by sgaichas** [comment]
`plot_chl_pp` seems broken; do we have a list of plot functions that still need updating? thanks

**Comment by BBeltz1** [comment]
Sorry I should have mentioned. The plot function for `chl_pp` is currently broken as a result of merging `chl_pp` and `phyto_size`. The plot functions will need to be combined to compensate.

The plot function for `engagement` will also break. It's used to generate the bubble plots that we decided not to use going forward. It breaks because Bobby's new submission does not include the 'EJ Rating' column.

Other than those, these [new indicators](https://github.com/NOAA-EDAB/ecodata/issues/174) also need plot functions as mentioned above.

I am planning to tackle as many of those as I can before Thursday, but wanted to pull these updates into `dev` first so I can work off of a new, clean branch. If you'd prefer I make those changes on this branch before we make that pull, I'm happy to amend my plans.

**Comment by BBeltz1** [comment]
Also for the new indicators, especially those that submitted image files but no code, I am planning to produce those catalog pages so we can review not only the plots but also the writing on Thursday. Happy to adjust that plan as well if you want.

**Review by sgaichas — APPROVED** [review]
I think go ahead and bring them in now if that is easier, I can build the package without any problems, and you have a list of the outstanding plot function issues

**Comment by BBeltz1** [comment]
Yes that would be my preference. Thanks Sarah!

**Pull request merged**
