### PR TITLE
corrected and adjusted plot functions based on editor and/or contributor feedback

### PR DESCRIPTION
**Pull request by BBeltz1**
corrected and/or adjusted the following plot functions:

- plot_rec_hms: set default shadedRegion argument to NULL
- plot_bottom_temp_comp: added additional argument for EPU
- plot_seasonal_oisst_anom: added additional argument for EPU
- plot_wind_port: made adjustments to reconcile changes made to underlying dataset

### CODE REVIEW

**Comment by BBeltz1** [comment]
@sgaichas ready for review

**Review by sgaichas — CHANGES_REQUESTED** [review]
the plots are not ordering by max value in `plot_wind_port`, they are alphabetical.
I am unsure if this has to do with a $ being in the variable name, I suggest removing that in the dataset and spelling out dollars or reverting to the previous data name. maybe merge both of these branches into your planned new branch now so we can diagnose more easily. thanks.

**Comment by BBeltz1** [comment]
yes i see that now. i'll start diagnosing.

**Review by sgaichas — APPROVED** [review]
looks good, thanks. I made a tiny adjustment to the seasonal OISST plot to match the bottom temp comp plot: removed legends for single EPU and put EPU in the title instead

**Pull request merged**
