### PR TITLE
fixes to wind tables and changes to bottom temp maps

### PR DESCRIPTION
**Pull request by BBeltz1**
Fixed a bug in get_wea_landings_rev that was preventing the wind tables from correctly updating.

Changed the color scale and window limits of plot_bottom_temp_seasonal_gridded per editor request.

### CODE REVIEW

**Comment by jcaracappa1** [comment]
plot_wind_revenue() for New England looks off by a factor of 10.

**Comment by BBeltz1** [comment]
I'll check Doug's source data.

**Comment by jcaracappa1** [comment]
I think the data is ok. The problem was that the plot defaults to landings but the yaxis still is labelled Dollars.

**Comment by BBeltz1** [comment]
Yes I see that in the plot function. The units are not adjusting to the varName used.

**Comment by BBeltz1** [comment]
added automatic y axis labeling based on varName argument to plot_wind_revenue

**Review by andybeet — APPROVED** [review]
Cant comment on revenue values but all builds well.

**Pull request merged**
