### PR TITLE
Update ecodata with corrected comdat and species groupings

### PR DESCRIPTION
**Pull request by BBeltz1**
Replaced old comdat datafile with Sean's final corrections. Herring data for 2022 was added. Solution for revenue errors was deployed.

Replaced old species_groupings file with new SOE24 groupings.

### CODE REVIEW

**Comment by BBeltz1** [comment]
@andybeet corrections/updates to comdat and species groupings ready for review.

**Comment by sgaichas** [comment]
I built this but am not seeing a 2022 data point for planktivores (herring) when I plot the NE human dimensions rmd; not sure what I'm doing wrong?

**Comment by sgaichas** [comment]
In this `comdat` dataset max year for Planktivore NEFMC managed species - Seafood Landings  is 2021; I think the herring landings integration didn't take

**Comment by andybeet** [comment]
@sgaichas i see that too now. looking over code. I did add Herring but must have then got dropped

**Comment by BBeltz1** [comment]
@andybeet @sgaichas this pull now includes the most recent corrections sent by andy

**Comment by sgaichas** [comment]
I can see the planktivores now in the plots, thanks for the fix!

**Pull request merged**
