### PR TITLE
New index plots + chl_pp

### PR DESCRIPTION
**Pull request by andybeet**
## New plotting functions

* `plot_benthos_index`
* `plot_zooplankton_index`

## Updates

* `plot_chl_pp` - nested `plot_phyto_size` within.
    * added an additional option to varName = "size"
    * added additional argument "EPU"
    * plots weekly baseline for year along with partial data
 * updated `chl_pp.r` to reflect both phyto size and chl, pp
 * removed `phyto_size.r`
 * `plot_aggregate_biomass` bug fix (removed unneeded filter)

## Other changes

* Created `benthos_index.r` and `zooplankton_index.r` data documentation files

### CODE REVIEW

**Comment by andybeet** [comment]
@BBeltz1 the phyto_size figure produced isn't correct. i think it is an issue with the data not the plot. Not sure exactly what is causing the problem but i think some rows are missing from the updated data set relative to what is in the `ecodata::phyto_size` data object.

**Comment by BBeltz1** [comment]
@sgaichas Ah I see the files I missed, my mistake. I've added `smallcopeALL` to the dataset. Sorry for the trouble.

Just to double check Sarah, is that now everything? 6 functional groups, 4 datafiles each (fall index, fall cog, spring index, spring cog)? The dataset now has 72 variables... 6 groups x 3 variables + 3 SEs x 2 seasons. Does that sound correct?

**Comment by sgaichas** [comment]
@BBeltz1 yes I think that sounds like the correct number, thanks for checking

**Comment by andybeet** [comment]
@sgaichas @BBeltz1. i'll fix those plots.

**Comment by andybeet** [comment]
Just noticed in the catalog submission (#122), it should be `benthos_index` not `benthic_index`. We should rename the data object, then i can update the plot functions etc

**Comment by BBeltz1** [comment]
I believe `benthos_index` was the originally proposed name, but there was a suggestion to switch it to `benthic_index`. It is now `benthic_index` everywhere except in the submission issues. I would propose that we leave the data object and plot function as `benthic_index` and change the data name in the issues to match. Unless @sgaichas has a strong preference for `benthos_index`.

**Comment by andybeet** [comment]
ok.  i changed the indicator name to `benthic_index` in the submission. Also changed the name to `zooplankton_index` for that submission too.

**Review by BBeltz1 — APPROVED** [review]
plotting for `benthic_index`, `zooplankton_index` and `chl_pp` are all working for me

**Comment by BBeltz1** [comment]
close #190

**Pull request merged**
